My_Blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog', include('app_blog.urls')),
    path('', views.index,name= 'index'),
]

urlpatterns += static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static (settings.STATIC_URL, document_root= settings.STATIC_ROOT)

app_blog/urls.py
from django.urls import path
from . import views


app_name= 'app_blog'


urlpatterns = [
    path ('', views.BlogList.as_view(), name='blog_list'),
    path('Write/', views.createBlog.as_view(), name= 'create_blog'),
    path('blog_details/<int:pk>', views.blog_details, name='blog_details'),
    path('liked/<int:pk>', views.liked , name= 'liked_post'),
    path('unliked/<int:pk>', views.unliked ,name ='unliked_post'),
    path('my-blog/' , views.MyBlogs.as_view() , name='my_blogs'),
    path('Edit-blog/<int:pk>' , views.UpdateBlog.as_view() , name ='edit_blog'),
    
]

app_login/urls.py
from django.urls import path
from . import views


app_name= 'app_login'


urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/' , views.user_change, name='user_change'),
    path('pass_change/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic , name='add_pro_pic'),
    path ('change-picture/', views.change_pro_pic, name='change_pro_pic')
    
]

app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class userProfile(models.Model):
    user = models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics')

app_login/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from django.contrib.auth.models import User
from .models import userProfile

class signUpForm(UserCreationForm):
    email = forms.EmailField(label='Email Address', required =True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

class UserProfileChange (UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name','password']

class profilePic(ModelForm) :
    class Meta:
        model = userProfile
        fields = ['profile_picture']
        

app_login/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login ,authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import signUpForm , UserProfileChange , profilePic



def sign_up(request):
    form = signUpForm()
    registered = False
    if request.method == "POST":
        form = signUpForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True

    context={'form':form, 'registered':registered}  
    return render(request,'app_login/signup.html',context)    


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                print("User logged in successfully")
                return redirect('app_blog:blog_list')
            else:
                print("Authentication failed")
        else:
            print("Form is invalid")

    return render(request, 'app_login/login.html', context={'form': form})
           
@login_required
def log_out(request):
    logout(request)
    messages.info(request,'user is logout')
    return redirect('app_login:login')
                
@login_required
def profile(request):
    context = {}
    return render ( request, 'app_login/profile.html', context)
@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST , instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)

    return render (request, 'app_login/changeProfile.html', context = {'form': form})        


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(instance=current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()

            changed = True
    return render(request , 'app_login/change_pass.html' , context = {'form':form , 'changed':changed})        
@login_required
def add_pro_pic(request):
    
    form = profilePic()
    if request.method == 'POST':
        form = profilePic(request.POST , request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return redirect ('app_login:profile')
    return render (request , 'app_login/pro_pic_add.html', context={'form':form})
@login_required
def change_pro_pic(request):
    form = profilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = profilePic(request.POST , request.FILES , instance =request.user.user_profile)
        if form.is_valid(): 
            form.save()
            return redirect ('app_login:profile')

    return render (request , 'app_login/pro_pic_add.html', context={'form':form})  

app_login/templates/app_login/changeProfile.html
{% extends 'base.html' %}
{% block title_block %} change profile {% endblock %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="button" class="btn btn-warning btn-sm"> change </button>



</form>

{% endblock content %}

app_login/templates/app_login/change_pass.html
{% extends 'base.html' %}
{% block title_block %} change pass {% endblock %}
{% block content %}
{% if changed %}
<div  class="alert alert-success"> password change successfully

</div>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="button" class="btn btn-warning btn-sm"> change </button>



</form>

{% endblock content %}

app_login/templates/app_login/login.html
{% extends 'base.html' %}
{% block title_block %} Login Page {% endblock %}
{% block content %}
<h2>LogIn:</h2>
<form action="{% url 'app_login:login' %}" method="POST">
   {{form.as_p}}
   {% csrf_token %}

    <button type="submit" class="btn btn-primary btn-sm">Log In</button>
</form>

{% endblock content %}

app_login/templates/app_login/pro_pic_add.html
{% extends 'base.html' %}
{% block title_block %} profile_pic_change {% endblock %}
{% block content %}

<h2>Add Your Profile Pic:</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p }}


    <button type="submit" class="btn btn-success btn-sm">Add </button>



</form>

{% endblock content %}

app_login/templates/app_login/profile.html
{% extends 'base.html' %}
{% block title_block %} profile {% endblock %}
{% block content %}
<h2>Your Profile</h2>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_picture}}"  class="rounded-circle" width="100px" >
<br>
<br>
<a href="{% url 'app_login:change_pro_pic' %}" class="btn btn-info btn-sm">Change profile pic</a>
{% else %}
<img src="/media/profile_pics/Default_img.jpg" class="rounded-circle" width="100px" >
<br>
<br>
<a href="{% url 'app_login:add_pro_pic' %}" class="btn btn-info btn-sm">Change profile pic</a>

{% endif %}
<p>Username:{{user.username}}</p>
<p>Email: {{user.email}}</p>
<p>Name: {{user.first_name}}  {{user.last_name}}</p>

<br>

<a href="{% url 'app_login:user_change' %}">change profile info</a>


{% endblock content %}

app_login/templates/app_login/signup.html
{% extends 'base.html' %}
{% block title_block %} Create New Account {% endblock %}
{% block content %}
{% if registered %}
<div class="alert alert-success">
    Account created succesfully! <a href="{% url 'app_login:login' %}">Login Here</a>

</div>
{% else %}
<h2>Create a New Account</h2>
<form action="" method="POST">
{{form.as_p}}
{% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already Have An Account? <a href="{% url 'app_login:login' %}">Login Here</a></p>
{% endif %}

{% endblock content %}