My_Blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog', include('app_blog.urls')),
    path('', views.index,name= 'index'),
]

urlpatterns += static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static (settings.STATIC_URL, document_root= settings.STATIC_ROOT)

app_blog/urls.py
from django.urls import path
from . import views


app_name= 'app_blog'


urlpatterns = [
    path ('', views.BlogList.as_view(), name='blog_list'),
    path('Write/', views.createBlog.as_view(), name= 'create_blog'),
    path('blog_details/<int:pk>', views.blog_details, name='blog_details'),
    path('liked/<int:pk>', views.liked , name= 'liked_post'),
    path('unliked/<int:pk>', views.unliked ,name ='unliked_post'),
    path('my-blog/' , views.MyBlogs.as_view() , name='my_blogs'),
    path('Edit-blog/<int:pk>' , views.UpdateBlog.as_view() , name ='edit_blog'),
    
]

app_login/urls.py
from django.urls import path
from . import views


app_name= 'app_login'


urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/' , views.user_change, name='user_change'),
    path('pass_change/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic , name='add_pro_pic'),
    path ('change-picture/', views.change_pro_pic, name='change_pro_pic')
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}"><img src="/media/blog.jpg" width="100px" alt=""></a>
          </li>
          {% if user.is_authenticated %}
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
              @{{user.username}}
  
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'app_blog:create_blog' %}">Write Blog</a>
              <a class="dropdown-item" href="{% url 'app_blog:my_blogs' %}">My Blogs</a>
              <a class="dropdown-item" href="{% url 'app_login:profile' %}">Your Profile</a>
              <hr>
              <a class="dropdown-item" href="{% url 'app_login:logout' %}">Logout</a>
              
             
  
  
            </div>
  
          </div>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_login:signup' %}">Sign Up</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_login:login' %}">LogIn</a>
          </li>
          {% endif %}
        </ul>
        
    </nav> 
    <div class="container" style="padding-top: 20px">
      {% block content %}

      {% endblock content%}

    </div>
    
    
    
</body>
</html>