My_Blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog', include('app_blog.urls')),
    path('', views.index,name= 'index'),
]

urlpatterns += static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static (settings.STATIC_URL, document_root= settings.STATIC_ROOT)

app_blog/urls.py
from django.urls import path
from . import views


app_name= 'app_blog'


urlpatterns = [
    path ('', views.BlogList.as_view(), name='blog_list'),
    path('Write/', views.createBlog.as_view(), name= 'create_blog'),
    path('blog_details/<int:pk>', views.blog_details, name='blog_details'),
    path('liked/<int:pk>', views.liked , name= 'liked_post'),
    path('unliked/<int:pk>', views.unliked ,name ='unliked_post'),
    path('my-blog/' , views.MyBlogs.as_view() , name='my_blogs'),
    path('Edit-blog/<int:pk>' , views.UpdateBlog.as_view() , name ='edit_blog'),
    
]

app_blog/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Blog(models.Model):
    Author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(default="", null=False,max_length=264)
    blog_content = models.TextField(verbose_name="Whats on your mind")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Image', blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta :
        ordering = ['-publish_date']


    def __str__(self):
        return self.blog_title


class comment(models.Model):
    blog = models.ForeignKey(Blog , on_delete=models.CASCADE, related_name='blog_comment')
    user =models.ForeignKey(User , on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']


    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog =models.ForeignKey(Blog , on_delete=models.CASCADE, related_name='liked_blog')
    user =models.ForeignKey(User , on_delete=models.CASCADE, related_name='liker_user')

    def __str__(self):
        return self.user + 'likes' + self.blog
    

        

app_blog/forms.py
from django import forms
from .models import Blog , comment


class commentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ['comment']

app_blog/views.py
from django.shortcuts import render , HttpResponseRedirect, redirect
from django.views.generic import CreateView , UpdateView , ListView , DetailView , DeleteView , View , TemplateView
from .models import Blog , comment , Likes
from django.urls import reverse , reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify
import uuid
from .forms import commentForm

# Create your views here.
class MyBlogs(LoginRequiredMixin , TemplateView):
    template_name ='app_blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ['blog_title','blog_content','blog_image']
    template_name = 'app_blog/edit_blog.html'

    def get_success_url(self):
        return reverse_lazy('app_blog:blog_details', kwargs={'pk': self.object.pk})

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/blog_list.html'
    


class createBlog(LoginRequiredMixin , CreateView):
    model = Blog
    template_name = 'app_blog/create_blog.html'
    fields = ['blog_title', 'blog_content', 'blog_image']

    def form_valid(self,form):
        blog_obj = form.save(commit=False)
        blog_obj.Author = self.request.user
        title = blog_obj.blog_title
        
        blog_obj.slug = slugify(blog_obj.blog_title)

        blog_obj.save()
        return redirect ('index')

def blog_details(request , pk ):
    blog = Blog.objects.get(id = pk)
    comment_form = commentForm
    already_liked =Likes.objects.filter(blog=blog, user = request.user)
    if already_liked:
        liked = True
    else:
        liked = False    
    if request.method == "POST":
        comment_form=commentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit = False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return redirect('app_blog:blog_details', pk = blog.id )

    context ={'blog':blog ,'comment_form':comment_form, 'liked':liked}
    return render(request , 'app_blog/blog_details.html' , context)
@login_required
def liked(request , pk):
    blog = Blog.objects.get( id = pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog,user=user)
    if not already_liked :
        liked_post= Likes(blog = blog, user = user)
        liked_post.save()
    return redirect ('app_blog:blog_details' , pk = blog.id )

@login_required
def unliked(request , pk):
    blog = Blog.objects.get( id = pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog,user=user)
    already_liked.delete()
    return redirect ('app_blog:blog_details' , pk = blog.id )

app_blog/templates/app_blog/blog_details.html
{% extends 'base.html' %}
{% block title_block %} {{ blog.blog_title }}   {% endblock title_block %}
{% block content %}
<div  class="row">
    <div class="col-sm-6">
        <h2>{{ blog.blog_title }}</h2>
        <h4>posted by:@{{ blog.Author }}</h4>
        <i><h6>Published on: {{ blog.publish_date }}</h6></i>
        <i><h6>updated on: {{ blog.update_date }}</h6></i>
        <h6>{{ blog.liked_blog.count }} likes | {{blog.blog_comment.count}} comments </h6>

    </div>
    <div class="col-sm-6">
        <img src="/media/{{blog.blog_image}}" width="100%" >

    </div>
<p>
    {{ blog.blog_content|linebreaks }}
</p> 
<hr>
  
</div>
{% if not liked %}
<a href="{% url 'app_blog:liked_post' pk=blog.id %}">
    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
</a>
{% else %}
<a href="{% url 'app_blog:unliked_post' pk=blog.id %}">
    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
</a> 
{% endif %} 

<div class="row">
    <div class="col-sm-6">
        <hr>
        <h5>Comment:</h5>
        {% for comment in blog.blog_comment.all %}
        <p><a href="">@{{ comment.user }}: {{ comment.comment }} <br> <h6>{{ comment.comment_date }}</h6></a></p>
        {% endfor %}

    </div>
    <div class="col-sm-6">
        <form  method="POST">
            {{comment_form.as_p}}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Comment</button>
              
        </form>

    </div>

</div>


{% endblock content %}

app_blog/templates/app_blog/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block content %}
{% for blog in blogs %}
<h3>{{blog.blog_title}}</h3>
<h6><i>{{blog.publish_date}}</i></h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'app_blog:blog_details' pk=blog.id  %}">Read More</a></p>
    <h6>Posted By: <a href="#">@{{blog.Author}}</a></h6>
    <h6>{{ blog.liked_blog.count }} likes | {{blog.blog_comment.count}} comments </h6>
    

  </div>
</div>
<hr>
{% endfor %}
{% endblock content %}

app_blog/templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% block title_block %}    {% endblock title_block %}
{% block content %}
<h2>Write Your Blog Here!</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>


{% endblock content %}

app_blog/templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% block title_block %} {{ blog.blog_title }}   {% endblock title_block %}
{% block content %}
{% if blog.Author == user %}
<form action="" method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit" name="button">Update</button>

{% else %}
<p>you are not allowed to view this page .404</p>     
</form>
{% endif %}

{% endblock content %}

app_blog/templates/app_blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %}  {{user}}  {% endblock title_block %}
{% block content %}

{% for blog in user.post_author.all %}

<h3>{{ blog.blog_title }}</h3>
<h6>{{ blog.publish_date }}</h6>
<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}"  width="100%">

    </div>
    <div class="col-sm-8">
        <p>{{ blog.blog_content |range_filter|linebreaks }}</p>
        <a href="{% url 'app_blog:blog_details' pk=blog.id  %}">Read More</a>

    </div>

</div>
<a href="{% url 'app_blog:edit_blog' pk=blog.id %}">Edit Blog</a>


{% endfor %}

{% endblock content %}